/**
 * Comprehensive list of South African Tertiary Institutions
 * Used across the website for consistency
 */

export const SOUTH_AFRICAN_INSTITUTIONS = [
  // Traditional Universities
  "University of Cape Town (UCT)",
  "University of the Witwatersrand (Wits)",
  "University of Pretoria (UP)",
  "Stellenbosch University (SU)",
  "University of KwaZulu-Natal (UKZN)",
  "Rhodes University (RU)",
  "University of Johannesburg (UJ)",
  "University of the Free State (UFS)",
  "North-West University (NWU)",
  "University of the Western Cape (UWC)",
  "Nelson Mandela University (NMU)",
  "University of South Africa (UNISA)",
  "University of Fort Hare (UFH)",
  "Walter Sisulu University (WSU)",
  "University of Limpopo (UL)",
  "University of Venda (UNIVEN)",
  "University of Zululand (UNIZULU)",
  "Sefako Makgatho Health Sciences University (SMU)",
  "Sol Plaatje University (SPU)",
  "University of Mpumalanga (UMP)",
  
  // Universities of Technology
  "Cape Peninsula University of Technology (CPUT)",
  "Central University of Technology (CUT)",
  "Durban University of Technology (DUT)",
  "Mangosuthu University of Technology (MUT)",
  "Tshwane University of Technology (TUT)",
  "Vaal University of Technology (VUT)",
  "Walter Sisulu University of Technology (WSU Tech)",
  
  // Comprehensive Universities
  "University of South Africa (UNISA)",
  
  // Private Higher Education Institutions
  "Monash South Africa",
  "Pearson Institute of Higher Education",
  "The Independent Institute of Education (IIE)",
  "Varsity College",
  "Boston City Campus",
  "Damelin",
  "CTI Education Group",
  "Milpark Education",
  "Rosebank College",
  "AFDA (The School for the Creative Economy)",
  "Vega School",
  "Red & Yellow Creative School of Business",
  "AAA School of Advertising",
  "Inscape Design College",
  "CityVarsity",
  "IMM Graduate School of Marketing",
  "Regent Business School",
  "MANCOSA",
  "Cornerstone Institute",
  "SA College of Applied Psychology (SACAP)",
  
  // Additional Colleges
  "Eduvos",
  "Richfield Graduate Institute of Technology",
  "The Da Vinci Institute",
  "College of Cape Town (CPUT)",
  "Northlink College",
  "South Cape TVET College",
  "False Bay TVET College",
  "Boland College",
  "West Coast TVET College",
  "Orbit TVET College",
  "Northumbria University (SA)",
  "Greenside Design Center",
  "Open Window Institute",
  "Friends of Design",
  "Elizabeth Galloway Academy of Fashion",
  "Cape Audio College",
  "SAE Institute South Africa",
  "Academy of Sound Engineering",
  "Media Design School",
  "Animation School",
  "Cape Town Creative Academy",
  "Shaw Academy South Africa",
  "Alison Courses South Africa",
  "GetSmarter (UCT Online)",
  "Business School Netherlands South Africa",
  "Henley Business School Africa",
  "Gordon Institute of Business Science (GIBS)",
  "USB Business School (Stellenbosch)",
  "Regenesys Business School",
  "Wits Business School",
  "UCT Graduate School of Business",
]

// Simplified list for select dropdowns (shorter display names)
export const INSTITUTION_OPTIONS = [
  { value: "uct", label: "University of Cape Town" },
  { value: "wits", label: "University of the Witwatersrand" },
  { value: "up", label: "University of Pretoria" },
  { value: "su", label: "Stellenbosch University" },
  { value: "ukzn", label: "University of KwaZulu-Natal" },
  { value: "ru", label: "Rhodes University" },
  { value: "uj", label: "University of Johannesburg" },
  { value: "ufs", label: "University of the Free State" },
  { value: "nwu", label: "North-West University" },
  { value: "uwc", label: "University of the Western Cape" },
  { value: "nmu", label: "Nelson Mandela University" },
  { value: "unisa", label: "University of South Africa (UNISA)" },
  { value: "ufh", label: "University of Fort Hare" },
  { value: "wsu", label: "Walter Sisulu University" },
  { value: "ul", label: "University of Limpopo" },
  { value: "univen", label: "University of Venda" },
  { value: "unizulu", label: "University of Zululand" },
  { value: "smu", label: "Sefako Makgatho Health Sciences University" },
  { value: "spu", label: "Sol Plaatje University" },
  { value: "ump", label: "University of Mpumalanga" },
  { value: "cput", label: "Cape Peninsula University of Technology" },
  { value: "cut", label: "Central University of Technology" },
  { value: "dut", label: "Durban University of Technology" },
  { value: "mut", label: "Mangosuthu University of Technology" },
  { value: "tut", label: "Tshwane University of Technology" },
  { value: "vut", label: "Vaal University of Technology" },
  { value: "monash", label: "Monash South Africa" },
  { value: "pearson", label: "Pearson Institute of Higher Education" },
  { value: "iie", label: "The Independent Institute of Education (IIE)" },
  { value: "varsity", label: "Varsity College" },
  { value: "boston", label: "Boston City Campus" },
  { value: "damelin", label: "Damelin" },
  { value: "cti", label: "CTI Education Group" },
  { value: "milpark", label: "Milpark Education" },
  { value: "rosebank", label: "Rosebank College" },
  { value: "afda", label: "AFDA (The School for the Creative Economy)" },
  { value: "vega", label: "Vega School" },
  { value: "redyellow", label: "Red & Yellow Creative School of Business" },
  { value: "aaa", label: "AAA School of Advertising" },
  { value: "inscape", label: "Inscape Design College" },
  { value: "cityvarsity", label: "CityVarsity" },
  { value: "imm", label: "IMM Graduate School of Marketing" },
  { value: "regent", label: "Regent Business School" },
  { value: "mancosa", label: "MANCOSA" },
  { value: "cornerstone", label: "Cornerstone Institute" },
  { value: "sacap", label: "SA College of Applied Psychology (SACAP)" },
  { value: "eduvos", label: "Eduvos" },
  { value: "richfield", label: "Richfield Graduate Institute of Technology" },
  { value: "davinci", label: "The Da Vinci Institute" },
  { value: "cct", label: "College of Cape Town" },
  { value: "northlink", label: "Northlink College" },
  { value: "southcape", label: "South Cape TVET College" },
  { value: "falsebay", label: "False Bay TVET College" },
  { value: "boland", label: "Boland College" },
  { value: "westcoast", label: "West Coast TVET College" },
  { value: "orbit", label: "Orbit TVET College" },
  { value: "northumbria", label: "Northumbria University (SA)" },
  { value: "greenside", label: "Greenside Design Center" },
  { value: "openwindow", label: "Open Window Institute" },
  { value: "friendsofdesign", label: "Friends of Design" },
  { value: "elizabethgalloway", label: "Elizabeth Galloway Academy of Fashion" },
  { value: "capeaudio", label: "Cape Audio College" },
  { value: "sae", label: "SAE Institute South Africa" },
  { value: "ase", label: "Academy of Sound Engineering" },
  { value: "mediadesign", label: "Media Design School" },
  { value: "animationschool", label: "Animation School" },
  { value: "ctcreative", label: "Cape Town Creative Academy" },
  { value: "getsmarter", label: "GetSmarter (UCT Online)" },
  { value: "bsn", label: "Business School Netherlands South Africa" },
  { value: "henley", label: "Henley Business School Africa" },
  { value: "gibs", label: "Gordon Institute of Business Science (GIBS)" },
  { value: "usb", label: "USB Business School (Stellenbosch)" },
  { value: "regenesys", label: "Regenesys Business School" },
  { value: "wbs", label: "Wits Business School" },
  { value: "uctgsb", label: "UCT Graduate School of Business" },
]
